### ISSUE TITLE
Alignment with blat failing with python exception

### ISSUE THREAD

**Issue by r78v10a07** [ablab/rnaquast#18]
I'm using rnaquast with blat and and Trinity assembled transcriptome.

```
  2023-07-06 20:10:51
  Getting DISTRIBUTION report...
    Drawing cumulative transcript / isoform length plot...

'dict_keys' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/bin/rnaQUAST.py", line 348, in <module>
    return_code = main_utils()
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/bin/rnaQUAST.py", line 311, in main_utils
    separated_reports[i_transcripts].get_separated_report\
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/share/rnaquast-2.2.3-0/report/SeparatedReport.py", line 57, in get_separated_report
    DistributionReport.DistributionReport([transcripts_metrics], db_genes_metrics, self.output_dir, logger, PRECISION)
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/share/rnaquast-2.2.3-0/report/DistributionReport.py", line 20, in __init__
    self.get_basic_plots(transcripts_metrics, db_genes_metrics, precision)
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/share/rnaquast-2.2.3-0/report/DistributionReport.py", line 41, in get_basic_plots
    self.get_transcript_length_plot(db_genes_metrics, transcripts_metrics, self.output_dir, precision, short_report_visible=True)
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/share/rnaquast-2.2.3-0/report/DistributionReport.py", line 161, in get_transcript_length_plot
    transcript_len_plot.plot_compare_distribution(self.short_report_plots)
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/share/rnaquast-2.2.3-0/report/UtilsPictures.py", line 154, in plot_compare_distribution
    step = Plot.get_step(self.def_step, [self.isoforms_distribution], self.num_points)
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/share/rnaquast-2.2.3-0/report/UtilsPictures.py", line 350, in get_step
    x_begin, x_end = cls.get_x_begins_ends_plot(distributions, False)
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/share/rnaquast-2.2.3-0/report/UtilsPictures.py", line 313, in get_x_begins_ends_plot
    x_begin = min(x_begin, min(distributions[i_distribution].keys()))
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2953, in min
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/net/intdev/cbb03/landsman/roberto/resources/conda/envs/rnaquast/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: 'dict_keys' object cannot be interpreted as an integer

ERROR! Exception caught!

```

Here is the full log
[rnaQUAST.log](https://github.com/ablab/rnaquast/files/11973957/rnaQUAST.log)

**Comment by andrewprzh** [comment]
Dear @r78v10a07 

Sorry for the late reply, was out of the office.

I might have seen this error, but I'm not sure I know how to reproduce that. For now you can use `--no_plots` option or try different matplotlib version.

Best
Andrey

**Comment by andrewprzh** [comment]
@r78v10a07 

I found the error in pylab imports, thanks a lot for the report!

The issue should be now fixed in https://github.com/ablab/rnaquast/releases/tag/v.2.2.4

Best
Andrey
