### ISSUE TITLE
name 'math' is not defined

### ISSUE THREAD

**Issue by rasskaz** [ablab/rnaquast#23]
rnaQUAST.py --test

`Traceback (most recent call last):
  File "/home/eavodiasova/miniconda3/envs/quast/bin/rnaQUAST.py", line 348, in <module>
    return_code = main_utils()
  File "/home/eavodiasova/miniconda3/envs/quast/bin/rnaQUAST.py", line 311, in main_utils
    separated_reports[i_transcripts].get_separated_report\
  File "/home/eavodiasova/miniconda3/envs/quast/share/rnaquast-2.2.3-0/report/SeparatedReport.py", line 57, in get_separated_report
    DistributionReport.DistributionReport([transcripts_metrics], db_genes_metrics, self.output_dir, logger, PRECISION)
  File "/home/eavodiasova/miniconda3/envs/quast/share/rnaquast-2.2.3-0/report/DistributionReport.py", line 20, in __init__
    self.get_basic_plots(transcripts_metrics, db_genes_metrics, precision)
  File "/home/eavodiasova/miniconda3/envs/quast/share/rnaquast-2.2.3-0/report/DistributionReport.py", line 41, in get_basic_plots
    self.get_transcript_length_plot(db_genes_metrics, transcripts_metrics, self.output_dir, precision, short_report_visible=True)
  File "/home/eavodiasova/miniconda3/envs/quast/share/rnaquast-2.2.3-0/report/DistributionReport.py", line 161, in get_transcript_length_plot
    transcript_len_plot.plot_compare_distribution(self.short_report_plots)
  File "/home/eavodiasova/miniconda3/envs/quast/share/rnaquast-2.2.3-0/report/UtilsPictures.py", line 154, in plot_compare_distribution
    step = Plot.get_step(self.def_step, [self.isoforms_distribution], self.num_points)
  File "/home/eavodiasova/miniconda3/envs/quast/share/rnaquast-2.2.3-0/report/UtilsPictures.py", line 350, in get_step
    x_begin, x_end = cls.get_x_begins_ends_plot(distributions, False)
  File "/home/eavodiasova/miniconda3/envs/quast/share/rnaquast-2.2.3-0/report/UtilsPictures.py", line 316, in get_x_begins_ends_plot
    if not math.isinf(x_end):
NameError: name 'math' is not defined

ERROR! Exception caught!
`
Adding a math import to rnaquast-2.2.3-0/report/UtilsPictures.py solves the problem

**Comment by andrewprzh** [comment]
@rasskaz 

Thanks for the report, this is known bug, which was fixed in version [2.2.4](https://github.com/ablab/rnaquast/releases/tag/v.2.2.4). 
However, I was never able to upload a newer version to bioconda due to its internal problems.

Best
Andrey
