### ISSUE TITLE
ERROR! Exception caught!

### ISSUE THREAD

**Issue by woeberdaniela** [ablab/rnaquast#24]
Hello! I´m trying to assess the quality of my de novo transcriptome assembly (using Trinity) with rnaQUAST 2.3.0 
`rnaQUAST.py -c "$trinity_file" -l "$file_left" -r "$file_right" -t 32`
$trinity_file is a FASTA file; $file_left and $file_right are forward and reverse reads.

I got the following error message:
```
Getting reference...

list index out of range
Traceback (most recent call last):
  File "/media/quickdisk/data/miniconda/envs/assembly_control/bin/rnaQUAST.py", line 376, in <module>
    return_code = main_utils(sys.argv)
  File "/media/quickdisk/data/miniconda/envs/assembly_control/bin/rnaQUAST.py", line 100, in main_utils
    reference_dict = UtilsGeneral.list_to_dict(fastaparser.read_fasta(args.reference))
  File "/media/quickdisk/data/miniconda/envs/assembly_control/share/rnaquast-2.3.0-0/general/UtilsGeneral.py", line 106, in list_to_dict
    res[e[0].split()[0].strip()] = e[1].strip()
IndexError: list index out of range

ERROR! Exception caught!

In case you have troubles running rnaQUAST, you can submit the issue to github.com/ablab/rnaquast/issues
Please provide us with rnaQUAST.log file from the output directory.
```

I´m sorry if it´s an obvious issue, I´m new to transcriptomics and would be glad if someone could help me!

**Comment by andrewprzh** [comment]
Dear @woeberdaniela 

Unfortunately, rnaQUAST works only when the reference genome is provided. Also, `-l` and `-r` options in rnaQUAST are not for providing left and right reads.

Best
Andrey

**Comment by woeberdaniela** [comment]
I understand, thank you for your reply!
